#
# Students' Makefile for the Malloc Lab
#

CC = gcc -g
CFLAGS = -Wall

# 待补充
OBJS = xxxx.o

mmdriver: $(OBJS)
# 待补充gcc命令（使用变量）
	xxx

#待补充
mmdriver.o: xxxx.h
memlib.o: xxxx.h
mm.o: xxxx.h

clean:
	rm -f *~ *.o mmdrive


