# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ubuntu/COD2020/实验文件/lab3/lab_3/lab_3.srcs/sources_1/ip/dist_data_ram/dist_data_ram.xci
# IP: The module: 'dist_data_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ubuntu/COD2020/实验文件/lab3/lab_3/lab_3.srcs/sources_1/ip/dist_data_ram/dist_data_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dist_data_ram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/ubuntu/COD2020/实验文件/lab3/lab_3/lab_3.srcs/sources_1/ip/dist_data_ram/dist_data_ram.xci
# IP: The module: 'dist_data_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ubuntu/COD2020/实验文件/lab3/lab_3/lab_3.srcs/sources_1/ip/dist_data_ram/dist_data_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dist_data_ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
