# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ubuntu/COD2020/lab2/Lab_2/Lab_2.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.xci
# IP: The module: 'dist_mem_gen_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ubuntu/COD2020/lab2/Lab_2/Lab_2.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dist_mem_gen_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/ubuntu/COD2020/lab2/Lab_2/Lab_2.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.xci
# IP: The module: 'dist_mem_gen_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ubuntu/COD2020/lab2/Lab_2/Lab_2.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dist_mem_gen_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
